### ISSUE TITLE
All responses return empty bodies

### ISSUE THREAD

**Issue by syrm** [sim642/whatpulse#6]
Hello,

I tried every /dev/input/eventX i can't get any result for keyboard or mouse.

**Comment by sim642** [comment]
* You need read permission on the eventX file. I think I have the permissions in my user because the `setup-input-permissions.sh` script from the official Whatpulse client has set up the necessary `input` group and udev rules. The script isn't specific to the official client so it should be sufficient to give your user the required permissions via the `input` group if you don't want to set up the permissions somehow yourself.
* [`cat /proc/bus/input/devices`](https://stackoverflow.com/a/15052092/854540) to find out which input devices correspond to which eventX files.
* `evtest /dev/input/eventX` to see events from a given stream.
* Entries in `/dev/input/by-path` should work too but have more descriptive names.

**Comment by syrm** [comment]
Indeed with evtest i found the right device. But now nothing is uploaded, maybe whatpulse website block me.

**Comment by sim642** [comment]
If there are any errors they should appear in `stdout.log` or `stderr.log` I think. I haven't heard of anyone getting blocked from Whatpulse by using this.

**Comment by syrm** [comment]
Now i can't run it : 
whatpulsed                                                                                                     master ◼

Traceback (most recent call last):
  File "/usr/bin/whatpulsed", line 11, in <module>
    load_entry_point('whatpulse==1.0.0', 'console_scripts', 'whatpulsed')()
  File "/usr/lib/python3.6/site-packages/whatpulsed/whatpulsed.py", line 239, in main
    setup()
  File "/usr/lib/python3.6/site-packages/whatpulsed/whatpulsed.py", line 60, in setup
    wp.client_login()
  File "/usr/lib/python3.6/site-packages/whatpulse/client.py", line 50, in client_login
    res = self.s.request(ClientLoginRequest(self.userid, self.computerid, self.hash))
  File "/usr/lib/python3.6/site-packages/whatpulse/session.py", line 49, in request
    return self.requests([req])[0]
  File "/usr/lib/python3.6/site-packages/whatpulse/session.py", line 39, in requests
    tree = etree.fromstring(r.text, self.parser)
  File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119128)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117686)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:111673)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 646, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106750)
  File "<string>", line 0
lxml.etree.XMLSyntaxError

**Comment by syrm** [comment]
I deleted json and changed version to 2.8.1 in whatpulse/config.py and now : 
whatpulsed

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/whatpulsed/whatpulsed.py", line 51, in setup
    with open(STATE_FILE, 'r') as state_file:
FileNotFoundError: [Errno 2] No such file or directory: 'whatpulsed.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/whatpulsed", line 11, in <module>
    load_entry_point('whatpulse==1.0.0', 'console_scripts', 'whatpulsed')()
  File "/usr/lib/python3.6/site-packages/whatpulsed/whatpulsed.py", line 239, in main
    setup()
  File "/usr/lib/python3.6/site-packages/whatpulsed/whatpulsed.py", line 69, in setup
    wp.try_login(config['login']['email'], config['login']['password'])
  File "/usr/lib/python3.6/site-packages/whatpulse/client.py", line 28, in try_login
    res = self.s.request(TryLoginRequest(self.email, self.password))
  File "/usr/lib/python3.6/site-packages/whatpulse/session.py", line 49, in request
    return self.requests([req])[0]
  File "/usr/lib/python3.6/site-packages/whatpulse/session.py", line 39, in requests
    tree = etree.fromstring(r.text, self.parser)
  File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119128)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117686)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:111673)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 646, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106750)
  File "<string>", line 0
lxml.etree.XMLSyntaxError

**Comment by sim642** [comment]
`stdout.log` should contain all the responses received from Whatpulse APIs even before they're parsed so that might give a clue why the parsing fails. Or maybe if it's on "line 0" there is no response at all because of some error with [the request made here](https://github.com/sim642/whatpulse/blob/4860be931f4eb66ab118895f6b2e01356bddacc2/whatpulse/session.py#L37). There isn't much of error handling happening around this project so it's quite brittle and unpolished.

I have been running whatpulsed for a long time (over a year) continuously and it's been fine but I'm unsure if any changes to Whatpulse APIs or some dependent library updates may have broken things.

**Comment by syrm** [comment]
These files are empty.
But in session.py at line 39 r.text is an empty string

**Comment by syrm** [comment]
I tried with postman to do a POST on https://client.whatpulse.org/v1.1/ with data : 
<?xml version='1.0' encoding='UTF-8'?>
<client>
<requests>
<request type="trylogin">
<type_os>linux</type_os>
<client_version>2.8.1</client_version>
<email>my email</email>
<password>my password</password>
</request>
</requests>
</client>

empty string too

**Comment by sim642** [comment]
Very odd. Testing out now I can see the issue myself too. The whatpulsed client I've been running for a year was pulsing daily until 2017-08-16 but errored after that as well.

I've looked at the traffic from the official client using `mitmproxy` again and it seems to be fine. In fact I can't even see a difference in the requests being made which puzzles me because the requests from the official client work fine.

**Comment by sim642** [comment]
I think I managed to hunt down the reason for these empty responses and fix it.
